    #INCLUDE <P16F877A.INC>
    __CONFIG B'11110100011000'

    ORG 0X0000
    GOTO MAIN

    ORG 0X0100
    GOTO INT_SERV

MAIN
    CLRF STATUS

    CLRF PORTB
    CLRF PORTC

    BANKSEL TRISB
    MOVLW 0XFF
    MOVWF TRISB

    BANKSEL TRISC
    MOVLW 0X00
    MOVWF TRISC

    BANKSEL OPTION_REG
    MOVLW 0X7F
    MOVWF OPTION_REG
    BANKSEL PORTD

    CLRF INTCON		;CLEAR ALL INTERRUPTION FLAG
    BSF INTCON, INTE	;ENABLE EXTERNAL INTERRUPTION
    BSF INTCON, GIE	;ENABLE GLOBAL INTERRUPTION

START	;LOOP UNTIL INTERRUPTION
    GOTO START

INT_SERV
    BANKSEL PORTC
    BSF PORTC,RC6

    CBLOCK
    D0
    D1
    ENDC

    ;7 SECONDS DELAY
    ;1398 CYCLES
    MOVLW    0X17
    MOVWF    D0
    MOVLW    0X02
    MOVWF    D1
DELAY_0
    DECFSZ   D0, F
    GOTO     $+2
    DECFSZ   D1, F
    GOTO     DELAY_0

    ;2 CYCLES
    GOTO     $+1
    BCF PORTC,RC6

    BCF INTCON, INTF	;MANUALLY CLEAR INTERRUPTION FLAG WHEN FINISH
    RETFIE	;RETURN FROM INTERRUPTION

    END
