    #INCLUDE <P16F877A.INC>
    __CONFIG B'11110100011000'
    ORG 0X0000
    GOTO MAIN

    ORG 0X0010
    GOTO INT_SERV

    CBLOCK 0X0020
    MORE_RED
    MORE_GREEN
    RED_D0
    RED_D1
    GREEN_D0
    GREEN_D1
    YELLOW_D0
    YELLOW_D1
    ENDC

ORG 0X0045
MAIN
    CLRF STATUS

    CLRF PORTB
    CLRF PORTC

    BANKSEL TRISB
    MOVLW 0XFF
    MOVWF TRISB

    BANKSEL TRISC
    MOVLW 0X00
    MOVWF TRISC

    BANKSEL OPTION_REG
    MOVLW 0X7F
    MOVWF OPTION_REG
    BANKSEL PORTD

    CLRF INTCON		;CLEAR ALL INTERRUPTION FLAG
    BSF INTCON, INTE	;ENABLE EXTERNAL INTERRUPTION
    BSF INTCON, GIE	;ENABLE GLOBAL INTERRUPTION
    BCF INTCON, INTF
    BCF MORE_GREEN, 0
    BCF MORE_RED, 0

    BANKSEL PORTC

START
    BTFSC MORE_GREEN,0; SKIP IF 0
    BSF PORTC,RC6

    ;SET GREEN TIME; MORE_GREEN = 0 10 SEC, MORE_GREEN = 1 20 SEC
    MOVLW    0x1A
    BTFSC MORE_GREEN,0; SKIP IF 0
    MOVLW    0x3A
    MOVWF GREEN_D0

    MOVLW    0x02
    BTFSC MORE_GREEN,0; SKIP IF 0
    MOVLW    0x03
    MOVWF GREEN_D1
    BCF MORE_GREEN, 0

    ;SET RED TIME MORE_RED = 0 10 SEC, MORE_RED = 1 20 SEC
    MOVLW    0x1E
    BTFSC MORE_RED,0; SKIP IF 0
    MOVLW    0x3B
    MOVWF RED_D0

    MOVLW    0x02
    BTFSC MORE_RED,0; SKIP IF 0
    MOVLW    0x03
    MOVWF RED_D1

    ;SET YELLOW TIME
    MOVLW    0x1E
    MOVWF YELLOW_D0
    MOVLW    0x02
    MOVWF YELLOW_D1

    BCF MORE_RED, 0
    NOP
    NOP
    BCF PORTC,RC6
    BSF PORTC,RC0
    GOTO CHECK_RED_RB2

CHECK_RED_RB2
    BTFSS PORTB,RB2;SKIP IF ZERO
    GOTO  SET_RED_RED
    DECFSZ   RED_D0, F
    GOTO     $+2
    DECFSZ   RED_D1, F
    GOTO CHECK_RED_RB2
    BCF PORTC,RC0
    BSF PORTC,RC3
    GOTO  CHECK_YELLOW_RB2

SET_RED_RED
    BSF MORE_RED,0
    GOTO  KEEP_RED2

KEEP_RED
    NOP
    NOP
KEEP_RED2
    DECFSZ   RED_D0, F
    GOTO     $+2
    DECFSZ   RED_D1, F
    GOTO KEEP_RED
    BCF PORTC,RC0
    BSF PORTC,RC3
    GOTO  KEEP_YELLOW;2

    ;YELLOW
CHECK_YELLOW_RB2
    BTFSS PORTB,RB2;SKIP IF ZERO
    GOTO  SET_RED_YELLOW
    DECFSZ   YELLOW_D0, F
    GOTO     $+2
    DECFSZ   YELLOW_D1, F
    GOTO CHECK_YELLOW_RB2
    BCF PORTC,RC3
    BSF PORTC,RC6
    GOTO  CHECK_GREEN_RB2

SET_RED_YELLOW
    BSF MORE_RED,0
    GOTO  KEEP_YELLOW2

KEEP_YELLOW
    NOP
    NOP
KEEP_YELLOW2
    DECFSZ   YELLOW_D0, F
    GOTO     $+2
    DECFSZ   YELLOW_D1, F
    GOTO KEEP_YELLOW
    BCF PORTC,RC3
    BSF PORTC,RC6
    GOTO  KEEP_GREEN;2

CHECK_GREEN_RB2
    BTFSS PORTB,RB2;SKIP IF ZERO
    GOTO  SET_RED_GREEN
    DECFSZ   GREEN_D0, F
    GOTO     $+2
    DECFSZ   GREEN_D1, F
    GOTO CHECK_GREEN_RB2
    GOTO  START

SET_RED_GREEN
    BSF MORE_RED,0
    GOTO  KEEP_GREEN2

KEEP_GREEN
    NOP
    NOP
KEEP_GREEN2
    DECFSZ   GREEN_D0, F
    GOTO     $+2
    DECFSZ   GREEN_D1, F
    GOTO KEEP_GREEN
    GOTO  START;2

INT_SERV
    BSF MORE_GREEN,0
    BCF INTCON, INTF	;MANUALLY CLEAR INTERRUPTION FLAG WHEN FINISH
    RETFIE	;RETURN FROM INTERRUPTION

    END
