
    ;ENABLE PORTC AND D AS OUTPUT
    LDI R16, 0XFF
    OUT DDRD,R16

    LDI R16, 0X7
    OUT DDRC,R16

    ;Function set: 2 Line, 8-bit, 5x7 dots
    LDI R16, 0X04
    OUT PORTC,R16

    LDI R16, 0X38
    OUT PORTD,R16

    LDI R16, 0X00
    OUT PORTC,R16

    ;Display on, Cursor blinking command
    LDI R16, 0X04
    OUT PORTC,R16

    LDI R16, 0X0F
    OUT PORTD,R16

    LDI R16, 0X00
    OUT PORTC,R16

    ;Clear LCD
    LDI R16, 0X04
    OUT PORTC,R16

    LDI R16, 0X01
    OUT PORTD,R16

    LDI R16, 0X00
    OUT PORTC,R16

    ;Entry mode, auto increment with no shift
    LDI R16, 0X04
    OUT PORTC,R16

    LDI R16, 0X06
    OUT PORTD,R16

    ;ENABLE AND RS ON
    LDI R16, 0X05
    OUT PORTC,R16

    ;SET CARACTER '*'
    LDI R16,'A'
    OUT PORTD,R16

    ;ENABLE DOWN RS ON, LOAD VALUE
    LDI R16, 0X01
    OUT PORTC,R16

    LDI R16, 0X00
    OUT PORTC,R16

    RJMP CHECK_BUTTON

SET_FIRSTLINE:
    ;LOAD LINE CONTENT TO Z
    LDI ZH, HIGH(2*LINE1)
    LDI ZL, LOW(2*LINE1)

    ;Sets DDRAM address so that the cursor is positioned at the head of the FIRST line.
    LDI R17, 0X04
    OUT PORTC,R17

    LDI R17, 0X02
    OUT PORTD,R17

    LDI R17, 0X00
    OUT PORTC,R17

    LDI R16, 0X00

FIRSTLINE:
    ;ENABLE AND RS ON
    LDI R17, 0X05
    OUT PORTC,R17

    ;SET CARACTER Z TO PORTD, THEN Z++ SO NEXT RUN SET THE NEXT CHARACTER
    LPM R0,Z+
    OUT PORTD,R0

    ;ENABLE DOWN RS ON, LOAD VALUE
    LDI R17, 0X01
    OUT PORTC,R17

    CPI R16,0XF
    BREQ CHECK_BUTTON;IF R16 == 0XF JUMP TO LOOP, LAST AVAILABLE CHARACTER OF LINE HAS BE SHOWED
    INC R16

    RJMP FIRSTLINE
SET_SECONDLINE:
    ;LOAD LINE CONTENT TO Z
    LDI ZH, HIGH(2*LINE2)
    LDI ZL, LOW(2*LINE2)

    ;Sets DDRAM address so that the cursor is positioned at the head of the FIRST line.
    LDI R17, 0X04
    OUT PORTC,R17

    LDI R17, 0X02
    OUT PORTD,R17

    LDI R17, 0X00
    OUT PORTC,R17

    LDI R16, 0X00
SECONDLINE:
    ;ENABLE AND RS ON
    LDI R17, 0X05
    OUT PORTC,R17

    ;SET CARACTER Z TO PORTD, THEN Z++ SO NEXT RUN SET THE NEXT CHARACTER
    LPM R0,Z+
    OUT PORTD,R0

    ;ENABLE DOWN RS ON, LOAD VALUE
    LDI R17, 0X01
    OUT PORTC,R17

    CPI R16,0XF
    BREQ CHECK_BUTTON;IF R16 == 0XF JUMP TO LOOP, LAST AVAILABLE CHARACTER OF LINE HAS BE SHOWED
    INC R16

    RJMP SECONDLINE

LINE1:
    .DB "TESTE_FRASE_01__"

LINE2:
    .DB "TESTE_FRASE_02__"

CHECK_BUTTON:
    IN R16,PINC3
    CPI R16,0X01
    BREQ SET_FIRSTLINE;IF PC3 == 0X01 JUMP TO SET_FIRSTLINE, LAST AVAILABLE CHARACTER HAS BE SET

    IN R17,PINC4
    CPI R17,0X01
    BREQ SET_SECONDLINE;IF PC3 == 0X01 JUMP TO SET_SECONDLINE, LAST AVAILABLE CHARACTER HAS BE SET

    RJMP CHECK_BUTTON
